spring.application.name=aiagent
server.port=${PORT:8085}
server.address=0.0.0.0
groq.api.key=${GROQ_KEY}
spring.datasource.url=jdbc:postgresql://ep-orange-wave-ahidwjfz.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_OiJXcIeG3k1L
internal.api.key=gymflow-secret-connect-2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret=GymFlowMasterSecurityKey2026SuperSecretDoNotShare!